language: android

android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-15

jdk:
  - oraclejdk8

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "kKGfhOpP31VZBUcNw5P9M5OuIaa+sKOWsMpA1VfZohcOAkZRRvszu4yVwncno5YwXu4NVWfconA+9H92Tv6cA+CpP8ppjj5thH1ZTSE+I/L1VCiy3JeGMT/AdVZ5f0ElxDXMLfV+7dfZqIbjzTmRnUbO09CyL385b7I/1DjPGCE="
    - secure: "tCicrfEMfsS/Ccj0XdKERJk2bFMj/Qn6HIrqzKVemfu1k9jQQeab1yixQaOiMRGXoyhlmsSQGPSXFPqqO5UiOU0smSPbefZeKgDLG+vzdXooPFsu00N6+iqCmAd8cIMG4VHp42ZYMXEnVWyRhYxoHJM5IkOMB2nzYyBCzUnzZME="

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle
